import { DifficultyLevel } from '../../types/api';
import { SequencePuzzleConfig } from './types';

export const SEQUENCE_CONFIGS: Record<DifficultyLevel, SequencePuzzleConfig> = {
  easy: {
    difficulty: 'easy',
    activityTitle: 'Making a Cup of Tea',
    promptText: 'Tap the steps in order to make warm tea:',
    stepCount: 3,
    steps: [
      {
        id: 'tea-step-1',
        order: 1,
        title: 'Get Cup',
        description: 'Place a clean cup on the counter',
        iconName: 'cafe',
        badgeLabel: 'Cup',
      },
      {
        id: 'tea-step-2',
        order: 2,
        title: 'Put Tea Bag',
        description: 'Drop the tea bag inside the cup',
        iconName: 'pricetag',
        badgeLabel: 'Tea Bag',
      },
      {
        id: 'tea-step-3',
        order: 3,
        title: 'Pour Hot Water',
        description: 'Pour steaming hot water into cup',
        iconName: 'water',
        badgeLabel: 'Hot Water',
      },
    ],
  },
  medium: {
    difficulty: 'medium',
    activityTitle: 'Brushing Your Teeth',
    promptText: 'Put the morning brushing steps in the right order:',
    stepCount: 4,
    steps: [
      {
        id: 'teeth-step-1',
        order: 1,
        title: 'Hold Toothbrush',
        description: 'Take your toothbrush in hand',
        iconName: 'hand-right',
        badgeLabel: 'Brush',
      },
      {
        id: 'teeth-step-2',
        order: 2,
        title: 'Squeeze Toothpaste',
        description: 'Put toothpaste onto the bristles',
        iconName: 'color-palette',
        badgeLabel: 'Paste',
      },
      {
        id: 'teeth-step-3',
        order: 3,
        title: 'Brush Teeth',
        description: 'Brush all your teeth gently',
        iconName: 'happy',
        badgeLabel: 'Brush',
      },
      {
        id: 'teeth-step-4',
        order: 4,
        title: 'Rinse with Water',
        description: 'Rinse mouth clean with fresh water',
        iconName: 'water',
        badgeLabel: 'Rinse',
      },
    ],
  },
  hard: {
    difficulty: 'hard',
    activityTitle: 'Getting Dressed for the Day',
    promptText: 'Arrange what to wear from first to last:',
    stepCount: 5,
    steps: [
      {
        id: 'dress-step-1',
        order: 1,
        title: 'Undergarments',
        description: 'Put on clean underclothes first',
        iconName: 'shield',
        badgeLabel: '1st Layer',
      },
      {
        id: 'dress-step-2',
        order: 2,
        title: 'Comfortable Shirt',
        description: 'Slide arms into your favorite shirt',
        iconName: 'shirt',
        badgeLabel: 'Shirt',
      },
      {
        id: 'dress-step-3',
        order: 3,
        title: 'Pants / Trousers',
        description: 'Pull on comfortable pants',
        iconName: 'male',
        badgeLabel: 'Pants',
      },
      {
        id: 'dress-step-4',
        order: 4,
        title: 'Warm Socks',
        description: 'Slip socks on both feet',
        iconName: 'footsteps',
        badgeLabel: 'Socks',
      },
      {
        id: 'dress-step-5',
        order: 5,
        title: 'Walking Shoes',
        description: 'Put on sturdy shoes and fasten them',
        iconName: 'walk',
        badgeLabel: 'Shoes',
      },
    ],
  },
};
